version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vantec_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vantec_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vantec_password}
      POSTGRES_DB: ${POSTGRES_DB:-gestor_cfdi}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./master_schema_vcore_vps.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - vantec_network

  api:
    build: .
    container_name: vantec_api
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vantec_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vantec_password}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-gestor_cfdi}
      VANTEC_SECRET_KEY: ${VANTEC_SECRET_KEY:-VANTEC_SECRET_KEY_CHANGEME}
    volumes:
      - ./storage:/storage # Mapeo crítico para Expedientes Virtuales
    ports:
      - "8000:80"
    networks:
      - vantec_network

networks:
  vantec_network:
    driver: bridge

volumes:
  postgres_data:
